name: cfc
description: A CLI tool to scaffold clean architecture feature folders in Flutter.
version: 1.0.8
homepage: https://github.com/arg0nath/cfc
repository: https://github.com/arg0nath/cfc
issue_tracker: https://github.com/arg0nath/cfc/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  cfc: cfc
dev_dependencies:
  test: ^1.26.3
dependencies:
  lints: ^6.0.0
