name: cfc
description: A CLI tool to scaffold clean architecture feature folders in Flutter.
version: 1.0.0
homepage: https://github.com/arg0nath/cfc
repository: https://github.com/arg0nath/cfc
environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  cfc: bin/cfc.dart
